// Mocks generated by Mockito 5.4.4 from annotations
// in guia_moteis/test/data/repository/motel_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:guia_moteis/data/datasource/motels_remote_datasource.dart'
    as _i3;
import 'package:guia_moteis/domain/entities/motel/motel.dart' as _i5;
import 'package:guia_moteis/domain/entities/response/response_list.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseList_0<T> extends _i1.SmartFake
    implements _i2.ResponseList<T> {
  _FakeResponseList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MotelsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotelsRemoteDatasource extends _i1.Mock
    implements _i3.MotelsRemoteDatasource {
  MockMotelsRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseList<_i5.Motel>> getMotels() => (super.noSuchMethod(
        Invocation.method(
          #getMotels,
          [],
        ),
        returnValue: _i4.Future<_i2.ResponseList<_i5.Motel>>.value(
            _FakeResponseList_0<_i5.Motel>(
          this,
          Invocation.method(
            #getMotels,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ResponseList<_i5.Motel>>);
}
